### Create Participant
POST http://localhost:8080/api/events/1/participants
Accept: application/json
Content-Type: application/json

{
  "nickname": "slavic",
  "email": "iuliasl05@gmail.com",
  "bic": "434324",
  "iban": "438784",
  "balance": null
}

###
GET http://localhost:8080/api/events/1/participants
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/api/events/2/participants/102
Accept: application/json
Content-Type: application/json

###
PUT http://localhost:8080/api/events/2/participants/102
Accept: application/json
Content-Type: application/json

{
  "nickname": "samira simona",
  "email": "iuliasl05@gmail.com",
  "bic": "434324",
  "iban": "438784",
  "balance": null
}

###
DELETE http://localhost:8080/api/events/4/participants/52
Accept: application/json
Content-Type: application/json


