### Create Tag
POST http://localhost:8080/api/events/1/tags
Accept: application/json
Content-Type: application/json

{
  "name": "Gifting Money"
}

### Get All Tags
GET http://localhost:8080/api/events/1/tags
Accept: application/json
Content-Type: application/json
